import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import Typography from '@mui/material/Typography'
import DrawerAppBar from '../components/topnav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className='bg-white dark:bg-slate-900'>
                <header>
                    <Typography variant='h4' component='div' className='dark:text-white'>
                        Logo
                    </Typography>
                    <DrawerAppBar />
                </header>
                <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
            </body>
        </html>
    )
}
